# Generated by Django 6.0.3 on 2026-03-21 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='imbd_id',
            new_name='imdb_id',
        ),
    ]
